frontend:
  replicaCount: 3
  image:
    repository: dishr/frontend
    tag: v1
  service:
    port: 80

backend:
  replicaCount: 3
  image:
    repository: dishr/backend
    tag: v1
  service:
    port: 4000

mongodb:
  image:
    repository: mongo
    tag: "8"

  service:
    port: 27017

  replicaCount: 1    

  persistence:
    enabled: true
    storage: 5Gi
    storageClass: gp2

ingress:
  enabled: true
  host: ""

aws:
  region: us-east-1