name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

# ==========================
# 1. Install & Build Check
# ==========================

  build:
    name: Build Application
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24


      - name: Install Dependencies
        run: |
          npm ci
          npm update


      - name: Build React Application
        run: |
          npm run build



# ==========================
# 2. Code Quality + Security
# ==========================

  security-scan:

    name: SonarQube and OWASP Scan

    needs: build

    runs-on: self-hosted


    steps:

      - name: Checkout Code
        uses: actions/checkout@v4



      # SonarQube Analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}



      # Clean previous OWASP reports

      - name: Clean Dependency Reports
        run: |
          sudo rm -rf reports
          mkdir reports



      # OWASP Dependency Check

      - name: OWASP Dependency Check

        uses: dependency-check/Dependency-Check_Action@main

        with:
          project: food-delivery
          path: .
          format: HTML
          out: reports


      # Save OWASP report

      - name: Upload OWASP Report

        uses: actions/upload-artifact@v4

        with:

          name: dependency-check-report

          path: reports



# ==========================
# 3. Docker Build & Security
# ==========================


  docker-build:


    name: Docker Build and Push

    needs: security-scan

    runs-on: self-hosted


    steps:


      - name: Checkout Code

        uses: actions/checkout@v4



      - name: Docker Login

        uses: docker/login-action@v4

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Build Docker Image

        run: |

          docker build \
          -t dishr/frontend:${{ github.sha }} .



      # Container Vulnerability Scan

      - name: Trivy Image Scan

        run: |

          trivy image \
          --exit-code 1 \
          --severity CRITICAL,HIGH \
          dishr/frontend:${{ github.sha }}



      - name: Push Docker Image

        run: |

          docker push dishr/frontend:${{ github.sha }}



# ==========================
# 4. Update Helm Chart
# ==========================


  update-helm:

    name: Update Helm Repository

    needs: docker-build

    runs-on: self-hosted


    steps:


      - name: Checkout Helm Repository

        uses: actions/checkout@v4

        with:

          repository: RanasingheDD/food-delivery-Helm-Chart

          token: ${{ secrets.GH_TOKEN }}

          path: /


      - name: Update Image Tag

        working-directory: /

        run: |

          sed -i \
          "s/tag:.*/tag: ${{ github.sha }}/" \
          values.yaml



      - name: Commit and Push Changes

        working-directory: helm-repo

        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"


          git add .


          git commit \
          -m "Update image tag to ${{ github.sha }}" || echo "No changes"


          git push


# ==========================
# 5. Slack Failure Alert
# ==========================


  slack-notification:


    name: Slack Notification


    needs:

      - build

      - security-scan

      - docker-build

      - update-helm


    if: failure()


    runs-on: ubuntu-latest


    steps:


      - name: Send Slack Alert


        uses: slackapi/slack-github-action@v1.27.0


        with:


          payload: |

            {
              "text": "❌ CI/CD Pipeline Failed\n\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}"
            }


        env:


          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}